### ISSUE TITLE
Messages failed since 1.8.0

### ISSUE THREAD

**Issue by guillaumBrisard** [cloudfoundry-community/slack-notification-resource#106]
Hi,

I juste updated my resource from 1.7.1 to 1.8.0 with concourse 7.11.2 and this conf:
```yaml
  - name: mattermost-dev
    type: slack-notification
    source:
      disable: false
      insecure: true
      url: https://...
    icon: slack
```
```yaml
  put: mattermost-dev
  params:
    username: Concourse
    text_file: output-notif/notification.txt
    text: |
      ##### :heavy_check_mark: :green_book: **OK $BUILD_PIPELINE_NAME** - <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| $BUILD_JOB_NAME #$BUILD_NAME>
      $TEXT_FILE_CONTENT
```

And I have this log
```
* Host ... was resolved.
* IPv6: (none)
* IPv4: 
*   Trying :443...
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1736 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / x25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: C=FR; O=...; OU=...; CN=...
*  start date: Nov  7 14:58:07 2024 GMT
*  expire date: Nov  7 14:58:07 2025 GMT
*  issuer: C=FR; O=...; OU=...; CN=...
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to ... port 443
* using HTTP/2
* [HTTP/2] [1] OPENED stream for ...***WEBHOOK URL REDACTED***
* [HTTP/2] [1] [:method: POST]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: ...]
* [HTTP/2] [1] [:path: ***WEBHOOK URL REDACTED***]
* [HTTP/2] [1] [user-agent: curl/8.11.0]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [content-length: 326]
* [HTTP/2] [1] [content-type: application/x-www-form-urlencoded]
} [5 bytes data]
> POST ***WEBHOOK URL REDACTED*** HTTP/2
> Host: ...
> User-Agent: curl/8.11.0
> Accept: */*
> Content-Length: 326
> Content-Type: application/x-www-form-urlencoded
> 
} [326 bytes data]
* upload completely sent off: 326 bytes
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [130 bytes data]
< HTTP/2 400 
< content-type: application/json
< date: Tue, 13 May 2025 10:14:31 GMT
< permissions-policy: 
< referrer-policy: no-referrer
< vary: Accept-Encoding
< x-content-type-options: nosniff
< x-request-id: ...
< x-version-id: ...
< content-length: 172
* The requested URL returned error: 400
< 
{ [5 bytes data]
* Connection #0 to host ... intact
curl: (22) The requested URL returned error: 400
ERROR: sending the message to the Slack webhook has failed
```

I think it's related to https://github.com/cloudfoundry-community/slack-notification-resource/pull/97
