### ISSUE TITLE
support attachments

### ISSUE THREAD

**Issue by r3dDoX** [cloudfoundry-community/slack-notification-resource#14]
First off, thanks for this resource, it helped me out perfectly.

I saw that Slack supports attachments in its message format like so:

```
{
  "text": "some text",
  "attachments": [
    {
      "text": "attachment text",
      "color": "good"
    }
  ]
}
```

This allows the user to have quite nicely styled additions to a message with some options.

This resource could handle this as well. In yaml, this could look like:

```
params:
  text: "some text"
  attachments:
    - text: "attachment text"
       color: good
    - text: "event more text in another attachment"
```

I could also help developing if you'd like some help.
