### ISSUE TITLE
@mentions not working

### ISSUE THREAD

**Issue by ChristianGrube** [cloudfoundry-community/slack-notification-resource#16]
Not sure if the issue belongs to the plugin or the slackbot API but we were unable to mention people using this resource type.

When we do @here we get plain text in our slack channel rather than a proper mention + notification.

e.g.

``` yaml
  - name: test
    plan:
    - get: github
      trigger: true
    - task: test
      file: github/ci/tasks/test.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#engineering'
          text: 'Hi @here, test failed.'
```
