### ISSUE TITLE
Add /giphy option for slack alert

### ISSUE THREAD

**Issue by Wintermute1** [cloudfoundry-community/slack-notification-resource#36]
For example, a successful build occurs...
```
on_success:
     put: slack-alert
     params:
       channels: concourse
       text_file: build-dir/version.text
       text: |
         
         Result: $TEXT_FILE_CONTENT
       username: user
       icon_url: image.png
       giphy: /success
```
