### ISSUE TITLE
Allow for environment variables in all attachment fields

### ISSUE THREAD

**Issue by TimJones** [cloudfoundry-community/slack-notification-resource#37]
We would like to be able to fill in more fields with environment variables supported by Concourse.

```yaml
...
      - put: slack-engineering
        params:
          text_file: version/version
          channel: "#test-alerts"
          username: ConcourseCI
          attachments:
            - title: ${BUILD_PIPELINE_NAME} - ${BUILD_JOB_NAME}
              title_link: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
              color: good
              fields:
                - title: Status
                  value: OK!
                  short: true
                - title: Commit
                  value: <https://github.com/xxx/x/commit/${TEXT_FILE_CONTENT}|${TEXT_FILE_CONTENT}>
                  short: true
```
