### ISSUE TITLE
TEXT_FILE_CONTENT not interpolated in attachment text

### ISSUE THREAD

**Issue by adamwg** [cloudfoundry-community/slack-notification-resource#38]
I have a task that looks like this:

```yml
  put: notify-slack
  params:
    text_file: metadata/github_link
    text: "*success*"
    attachments:
      - text: "Job <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME|$BUILD_JOB_NAME> for $TEXT_FILE_CONTENT (<$ATC_EXTERNAL_URL/builds/$BUILD_ID|Details>)"
        color: "good"
```

A previous task generates the `metadata/github_link` file. I've verified that it is there and looks as expected in the notify-slack container.

In builds on August 1 the attachment text was getting interpolated as expected. In builds this week the `ATC_*` variables are being interpolated correctly, but `TEXT_FILE_CONTENT` ends up empty -
 i.e., the resulting attachment text looks like:

```text
Job build for (Details)
```

I haven't changed anything in my pipeline config in the meantime, so I believe this is a recently-introduced bug in the slack-notification-resource.
