### ISSUE TITLE
Mentions do not seem to work

### ISSUE THREAD

**Issue by olle-brkt** [cloudfoundry-community/slack-notification-resource#44]
Hi!

I'm trying to mention myself in slack messages sent. This do not seem to work for some reason. I've tried to different syntaxes, as suggested by: https://github.com/cloudfoundry-community/slack-notification-resource/issues/16

Maybe that only applies to `<!here>` and not `<!username>`?

Here's a super simple pipeline to reproduce the issue. Replace the username (unless your are also named `olle`) and the `((slack_webhook))` with your own unless you already happen to have that stored in a credential manager 😄 

```
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
resources:
- name: slack
  type: slack-notification
  source:
    url: ((slack_webhook))
jobs:
- name: hello-world
  plan:
  - get: slack
  on_success:
    do:
    - put: slack
      params:
        text: "<!olle> *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* succeded!"
    - put: slack
      params:
        text: "@olle *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* succeded!"
```
Output in slack:
<img width="407" alt="screen shot 2018-02-13 at 15 00 08" src="https://user-images.githubusercontent.com/31876997/36178721-aba896a6-10ce-11e8-853c-885deb379fc9.png">
