### ISSUE TITLE
hide of prameters not working

### ISSUE THREAD

**Issue by maandr** [cloudfoundry-community/slack-notification-resource#56]
As of today `hide` option does not work for me anymore, even when providing new `type: string` along with it.

```yaml
    - put: k8s
      params:
        chart: git/my-helm-chart
        values: git/my-helm-chart/values.yaml
        namespace: ((k8s_namespace))
        release: my-release
        override_values:
        - key: database.password
          value: ((database_password))
          type: string
          hide: true
```
