### ISSUE TITLE
v1.4.2 causes text files not to be recognized

### ISSUE THREAD

**Issue by enugentdt** [cloudfoundry-community/slack-notification-resource#57]
Hello

I noticed my builds started failing with the release of v1.4.2, and the error was that my text files weren't being found. Pinned the docker version to v1.4.1, and they've started working again. Is this a bug, or am I missing something?

Here's the job section of my pipeline:
```
jobs:
  - name: Build Project
    plan:
      - get: project
        trigger: true
      - task: Compile project
        file: project/ci/tasks/build.yml
        input_mapping: { repo: project }
        on_failure:
          put: alert
          params:
            text_file: message/failed
        on_success:
          put: alert
          params:
            text_file: message/passed
        on_abort:
          put: alert
          params:
            text_file: message/aborted
      - put: project-dist
        params: {
          "sync_dir" : "build/",
          "rsync_opts": ["-rzvvO"]
        }
      - put: keyval
        params:
          file: keyvalout/keyval.properties
```
