### ISSUE TITLE
check: 401 Unauthorized

### ISSUE THREAD

**Issue by mathias-ewald** [cloudfoundry-community/slack-notification-resource#60]
The resource worked fine for a while, now since a couple of days, I am getting this when the resource is checked:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest: 401 Unauthorized
```

My pipelines uses the resource as follows:

```
 resource_types:
   - name: slack-notification
     type: docker-image
     source:
       repository: cfcommunity/slack-notification-aesource
       tag: latest
...
resources:
   - name: slack
     type: slack-notification
     source:
       url: "https://hooks.slack.com/services/*********"
...
jobs:
...
   - name: deploy
     plan:
       ...
       - put: slack
         params:
           text_file: code/ci/slack/text.txt
```

I have tried generating a new hook url, but it shows the same error.
