### ISSUE TITLE
Passing URI using vault gives "curl: (3) Illegal characters found in URL"

### ISSUE THREAD

**Issue by sercanacar** [cloudfoundry-community/slack-notification-resource#65]
Hi,

Using Concourse v5 with Vault 1.0.1

Passing URI like so:
```
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:

  - name: slack-notify
    type: slack-notification
    source:
      url: ((slack_uri))
```

Build getting the following error in concourse

``` Illegal characters found in URL
* Closing connection -1
curl: (3) Illegal characters found in URL
