### ISSUE TITLE
Slack channel name

### ISSUE THREAD

**Issue by professor** [cloudfoundry-community/slack-notification-resource#85]
Slack currently creates a webhook per channel. The API for this concourse resource implies that you can change the slack channel name without changing the webhook. Unfortunately, changing the channel name in yml won't work...

```
---
jobs:
- name: some-job
  plan:
  - put: slack-alert
    params:
      channel: '#my_channel'
```

#my_channel needs to be the match the webhook url
